name: my first github action file
on : 
  push:
  workflow_dispatch:

jobs:
  first-jobs:
    runs-on: ubantu_latest
    
steps:
   - name: Print welcome message
     run: echo "Hello! This is my first GitHub Actions workflow."

   - name: Print current date
       run: date
    
